### ISSUE TITLE
MSMQ connectivity goes down - reconnect feature /throw exception feature missing

### ISSUE THREAD

**Issue by LekhaSahdev** [SteveBate/MiniBus#10]
Hi,
Currently - the retry feature is there for handler. But if the read MSMQ goes down - we are only logging message - line 59 MiniBusMessageQueue.cs. Post that neither is there a recreate of queue, nor is the exception thrown back t oaprent application so that parent application can recreate the bus.

Can this pls be handled.

**Comment by SteveBate** [comment]
This is now fixed in v0.2.0.
