### ISSUE TITLE
Submitting msgs to remote PCs

### ISSUE THREAD

**Issue by ghostsquad** [SteveBate/MiniBus#3]
Is there a configuration for incoming/outgoing ports? I didn't see any documentation in the readme about setting up subscribers on remote machines.

**Comment by SteveBate** [comment]
It's not pub/sub. It's "send" semantics only as the documentation states.
If minibus is running on a remote pc, it will have its own local queue
name. That's the name of the queue you use when sending from your local pc.

**Comment by ghostsquad** [comment]
thanks.
