### ISSUE TITLE
Multiple Handlers listening on same queue?

### ISSUE THREAD

**Issue by WestDiscGolf** [SteveBate/MiniBus#5]
Hi,

I've started using MiniBus as it looked like it would save me a lot of time dealing with MSMQ infrastructure setup, which it has! Thanks!

I'm trying to setup multiple message handlers on the same bus / queue instance and I am having issues with it determining which handler to fire if different messages are added to the same queue. Is this currently possible? If so, how would I go about setting up RegisterHandler / ReceiveAsync combination?

Cheers

**Comment by SteveBate** [comment]
Hi Adam,

I'm not sure what you mean by "if different messages are added to the same queue". When you say different messages do you mean different message types? Queues are always declared for specific type. 

Anyway, I've just pushed a commit with a new scenario in the sample program showing multiple handlers all being invoked for each message received. Maybe you can look at that and see if it helps?

Cheers

Steve

**Comment by WestDiscGolf** [comment]
Hi Steve,

The scenario I am looking at is setting up the following:

My message is:
```
    public class MyMessage<T>
    {
        public string Action { get; set; }
        public Guid Reference { get; set; }

        public T Payload { get; set; }
    }
```

And using it, currently, with either a string as T or a simple example POCO DTO ....

```
public class MyDtoPayload
    {
        public Guid MyGuid { get; set; } = Guid.NewGuid();

        public string MyAction { get; set; } = "MyAction";
    }
```

.... and sending it to the queue configured as below:

```
 var simplebus = new BusBuilder()
                 .InstallMsmqIfNeeded()
                 .DefineErrorQueue("errors")
                 .DefineReadQueue("messages")
                 .CreateLocalQueuesAutomatically()
                 .EnlistInAmbientTransactions()
                 .JsonSerialization()
                 .NumberOfRetries(3)
                 .CreateBus();
```

With the handlers and receiving setup as:

```
            simplebus.RegisterHandler(new MyMessageHandler());
            simplebus.RegisterHandler(new MyGenericHandler());

            simplebus.ReceiveAsync<MyMessage<string>>();
            simplebus.ReceiveAsync<MyMessage<MyDtoPayload>>();
```

The message handlers are:

```
class MyMessageHandler : IHandleMessage<MyMessage<string>>
    {

        public void Handle(MyMessage<string> p)
        {
            // do stuff with a string payload
        }
    }

    class MyGenericHandler : IHandleMessage<MyMessage<MyDtoPayload>>
    {
        public void Handle(MyMessage<MyDtoPayload> p)
        {
            // do stuff with a DTO payload
        }
    }
```

Then the message construction and Sending is similar to:

```
        var msg2 = new MyMessage<string>()
        {
            Action = $"Action: {count++}",
            Reference = Guid.NewGuid(),
            Payload = "this is the payload"
        };
        _bus.Send(msg2);

        var msg3 = new MyMessage<MyDtoPayload>()
        {
            Action = $"My T msg",
            Reference = Guid.NewGuid(),
            Payload = new MyDtoPayload()
        };
        _bus.Send(msg3);
```

Does that make sense?

Cheers

**Comment by SteveBate** [comment]
Hi Adam,

No, I don't think that's ever going to work. ReceiveAsync under the hood will peek messages off the queue and send them to every registered handler so your string handler would fire for the generic message as well as it's own and vice versa. When I said the queues are always declared for a specific type what you are effectively doing is attempting to bypass that "restriction" as a MyMessage<string> is not the same type as a MyMessage<MyDtoPayload>. 

It's not a use-case I ever considered and personally I would just declare two queues and have two bus instances each receiving off their own queue. Sorry! :)

Steve

**Comment by WestDiscGolf** [comment]
Hi Steve,

Thanks for the quick response!

Would it be possible to extend the ReceiveAsync to be cleverer with which handlers it sends it to? I'm starting to look at the code, and if I can get working make a pull request, but want to make sure I've understood the architecture correctly before making too many changes.

If not, then I think the multi queue will work for now :-)

Cheers

**Comment by SteveBate** [comment]
Right now the honest answer is I don't know. It's been a few years since I had my head buried deep in it so I'd have to spend time getting back up to speed but I feel like it _should_ be possible. As with most things, it's finding the time. I'll certainly try at some point to find some time to have a go because it does feel like a nice enhancement but you are of course welcome to give it a go too! :)

Steve

**Comment by WestDiscGolf** [comment]
Tried a couple of different ways but none successful yet. 

Nice layout of the code; I like the AOP style build up of the configured "pipeline" for handling messages :-)

**Comment by SteveBate** [comment]
Thanks! I am a big fan of the pipeline approach. A few years back I wrote about how I use it in normal, everyday enterprise apps. It's evolved/improved quite a bit since then but the premise is the same. If you're interested you can read it here ;)

[(https://eventuallyconsistent.net/2013/08/12/messaging-as-a-programming-model-part-1/)]

As for MiniBus, I too have been having a go today. The biggest problem I'm running into at the moment is the invocation of ReceiveAsync twice (once for each message type) which looks to expose a race condition as both compete for the same messages. This is to be expected as they are on the same queue but at the same time it does make me question if this is actually the right thing to be pursuing. I'll give it some more thought though. Not giving up just yet :)

**Comment by WestDiscGolf** [comment]
Sounds like you're running into the same issues as I have been experiencing!

The other ways I've been thinking about but not got working yet are ...

1) Have one RecieveAsync(), none generic, method and then inside that try and work out what the type is. This is the current headache with this approach, struggling how to determine the type of the message body at run time.

2) Have multiple RecieveAsync<T>() methods and in the ReceiveMessageHandler try and determine which handler to run by type of parameter

```
        public void Handle(Message msg)
        {
            T payload = GetPayload(msg);
            _logger.Log(string.Format("Message: {0} - Payload: {1}", msg.Label, msg.Body));

            foreach (var action in _handlers.Where(x => x.Method.GetParameters()[0].ParameterType == typeof(T)))
            {
                _logger.Log(string.Format("Message: {0} - Invoking registered handler", msg.Label));
                ((Action<T>)action)(payload);
            }           
        } 
```

However this is the race condition issue which sounds like you're experiencing as well.

The other option, which I'm just starting to put together to see if it works, will be to have a ReceiveAsync() method which takes a params of Type of message body types it can handle, eg

`_bus.ReceiveAsync(typeof(int), typeof(string));
`

Will see how far I get and let you know :-)
